using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Text;
using System.Windows.Forms;

using UltraSFV.Core;

namespace UltraSFV
{
	public partial class Form1 : Form
	{
		public Form1()
		{
			InitializeComponent();
		}

		private void button1_Click(object sender, EventArgs e)
		{
			bool Success = false;

			if (textBox1.Text.Length > 0)
			{
				DirectoryInfo dir = new DirectoryInfo(textBox1.Text);

				if (dir.Exists)
				{
					FileInfo SFVFile = new FileInfo(textBox1.Text + "/" + dir.Name + ".sfv");

					if (SFVFile.Exists)
					{
						if (MessageBox.Show("An UltraSFV files already exists in the directory!\n\nDo you with to overwrite?", "Overwrite File?", MessageBoxButtons.YesNo, MessageBoxIcon.Information) == DialogResult.No)
						{
							return;
						}
					}

					Success = RipDirectory(textBox1.Text);

					if (Success)
					{
						MessageBox.Show("SFV File Created", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);
					}
					else
					{
						MessageBox.Show("Unable to locate CRCs in file names", "Failure", MessageBoxButtons.OK, MessageBoxIcon.Warning);
					}
				}
				else
				{
					MessageBox.Show("Directory does not exist!", "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
				}
			}
			else
			{
				MessageBox.Show("Please select a directory to parse.", "Error", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
				textBox1.Focus();
			}
		}

		private void button2_Click(object sender, EventArgs e)
		{
			if (folderBrowserDialog1.ShowDialog() != DialogResult.Cancel)
			{
				textBox1.Text = folderBrowserDialog1.SelectedPath;
			}
			else
			{
				textBox1.Text = "";
			}
		}

		private bool RipDirectory(string directoryToSearch)
		{
			if (String.IsNullOrEmpty(directoryToSearch))
				throw new ArgumentNullException("directoryToSearch");

			bool FoundMatch = false;
			int MaxFileNameLen = 0;

			Hashtable SFVEntries = new Hashtable();

			DirectoryInfo di = new DirectoryInfo(directoryToSearch);

			if (di.Exists)
			{
				FileInfo[] DirectoryFiles = di.GetFiles();

				foreach (FileInfo File in DirectoryFiles)
				{
					string CRC = StringUtilities.FindCRC(File.Name);

					if (CRC != String.Empty)
					{
						SFVEntries.Add(File.Name, CRC);
						FoundMatch = true;
					}
					else
					{
						SFVEntries.Add("; " + File.Name, "NO CRC FOUND");
					}

					if (File.Name.Length > MaxFileNameLen)
					{
						MaxFileNameLen = File.Name.Length;
					}
				}

				using (StreamWriter sw = new StreamWriter(directoryToSearch + "/" + di.Name + ".sfv"))
				{
					sw.WriteLine("; File Generated By UltraSFV - www.ultrasfv.com\n");

					foreach (DictionaryEntry Entry in SFVEntries)
					{
						sw.WriteLine(StringUtilities.AddWhiteSpace(Entry.Key.ToString(), MaxFileNameLen + 4) + Entry.Value);
					}
				}
			}

			return FoundMatch;
		}
	}
}
